### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by kahoch** [angustrau/keyplus_firmware_builder#12]
Hi Angus, 
Thank you for your excellent work!
I'm completely new in front-end dev. Do yo have a detail guide to run this app?
I tried "npm install" then "yarn start", but got this:
"Failed to compile
 ./node_modules/material-ui/styles/withStyles.js 
Module not found: Can't resolve '@babel/runtime/core-js/map'"
How can I fix these error?

Thank you again!

**Comment by emilytrau** [comment]
Hi,
Thanks for checking out the project. I don't maintain this anymore, but there's a build hosted at https://angustrau.github.io/keyplus_firmware_builder/ . I would recommend trying VIA configurator as an alternative.

**Comment by kahoch** [comment]
I tried the one you host at first, it doesn't work.
And it seems VIA doesn't support keyplus😔😔
